theme: jekyll-theme-slate
title: Welcome to Soc La Taylor's page!
description: Pàgina personal de la Mariona Batalla Taylor, informàtica i dissenyadora gràfica, professora de cicles formatius d'informàtica.
